export const services = [
    { title: "Вывоз холодильников", href: "/services/fridge", icon: "🧊" },
    { title: "Вывоз микроволновок", href: "/services/microwave", icon: "🍱" },
    { title: "Вывоз стиральных машин", href: "/services/washing-machine", icon: "🧼" },
    { title: "Вывоз телевизоров", href: "/services/tv", icon: "📺" },
    { title: "Вывоз кондиционеров", href: "/services/air-conditioner", icon: "🌬️" },
    { title: "Вывоз утюгов", href: "/services/iron", icon: "👔" },
    { title: "Вывоз пылесосов", href: "/services/vacuum", icon: "🧹" },
    { title: "Вывоз духовых шкафов", href: "/services/oven", icon: "🍕" },
    { title: "Вывоз кофемашин", href: "/services/coffee-machine", icon: "☕" },
    { title: "Вывоз обогревателей", href: "/services/heater", icon: "🔥" },
    { title: "Вывоз газовых плит", href: "/services/gas-stove", icon: "🍲" },
    { title: "Вывоз электрических плит", href: "/services/electric-stove", icon: "⚡" },
    { title: "Вывоз тостеров", href: "/services/toaster", icon: "🍞" },
    { title: "Вывоз блендеров", href: "/services/blender", icon: "🥤" },
    { title: "Вывоз соковыжималок", href: "/services/juicer", icon: "🍊" },
    { title: "Вывоз посудомоек", href: "/services/dishwasher", icon: "🍽️" },
    { title: "Вывоз вытяжек", href: "/services/extractor", icon: "🌀" },
    { title: "Вывоз вентиляторов", href: "/services/fan", icon: "🌪️" },
    { title: "Вывоз принтеров", href: "/services/printer", icon: "🖨️" },
    { title: "Вывоз ноутбуков", href: "/services/laptop", icon: "💻" },
    { title: "Вывоз мониторов", href: "/services/monitor", icon: "🖥️" },
    { title: "Вывоз системных блоков", href: "/services/pc", icon: "🧠" },
    { title: "Вывоз сканеров", href: "/services/scanner", icon: "📠" },
    { title: "Вывоз факсов", href: "/services/fax", icon: "🧾" },
    { title: "Вывоз телефонов", href: "/services/phone", icon: "📱" },
];
