export const services = [
    {title: "Вывоз холодильников", href: "/services/fridge"},
    {title: "Вывоз микроволновок", href: "/services/microwave"},
    {title: "Вывоз стиральных машин", href: "/services/washing-machine"},
    {title: "Вывоз телевизоров", href: "/services/tv"},
    {title: "Вывоз кондиционеров", href: "/services/air-conditioner"},
    {title: "Вывоз утюгов", href: "/services/iron"},
    {title: "Вывоз пылесосов", href: "/services/vacuum"},
    {title: "Вывоз духовых шкафов", href: "/services/oven"},
    {title: "Вывоз кофемашин", href: "/services/coffee-machine"},
    {title: "Вывоз обогревателей", href: "/services/heater"},
    {title: "Вывоз газовых плит", href: "/services/gas-stove"},
    {title: "Вывоз электрических плит", href: "/services/electric-stove"},
    {title: "Вывоз тостеров", href: "/services/toaster"},
    {title: "Вывоз блендеров", href: "/services/blender"},
    {title: "Вывоз соковыжималок", href: "/services/juicer"},
    {title: "Вывоз посудомоек", href: "/services/dishwasher"},
    {title: "Вывоз вытяжек", href: "/services/extractor"},
    {title: "Вывоз вентиляторов", href: "/services/fan"},
    {title: "Вывоз принтеров", href: "/services/printer"},
    {title: "Вывоз ноутбуков", href: "/services/laptop"},
    {title: "Вывоз мониторов", href: "/services/monitor"},
    {title: "Вывоз системных блоков", href: "/services/pc"},
    {title: "Вывоз сканеров", href: "/services/scanner"},
    {title: "Вывоз факсов", href: "/services/fax"},
    {title: "Вывоз телефонов", href: "/services/phone"},
];
